### ISSUE TITLE
Problem running on Raspberry Pi

### ISSUE THREAD

**Issue by FredrikMeyer** [mujx/hakatime#10]
Hi!

I'm trying the `mujx/hakatime:latest-arm` image, and have some trouble getting hakatime to work.

Running `docker-compose -f docker-compose-deploy.yml up` works fine. I had to add `privileged: true`, because I got an error saying that it couldn't read the the time.

I also had to change
```
    ports:
      - "127.0.0.1:8080:8080"
```
to
```
    ports:
      - "0.0.0.0:8080:8080"
```
to be able to open the UI on my computer (and not the Pi). 

However, I cannot get past the login screen. First, I see `POST http://192.168.0.13:8080/auth/refresh_token 400 (Bad Request)` in the console log in Chrome. And when I try to register a new user, I see 
```
haka_db    | 2020-09-22 20:09:55.632 UTC [44] ERROR:  relation "users" does not exist at character 16
haka_db    | 2020-09-22 20:09:55.632 UTC [44] STATEMENT:   SELECT * FROM users WHERE username = $1
hakatime   | [2020-09-22 20:09:55][hakatime.server][Error][8332e554f052][PID 1][ThreadId 14][hakatime-0.1.0-inplace-libhaka:Haka.Authentication src/Haka/Authentication.hs:205:9] OperationException "relation \"users\" does not exist"
```
in the application logs.

For completeness, this is how my now edited Docker compose file looks like:
```
version: "3"
services:
  server:
    container_name: hakatime
    image: mujx/hakatime:latest-arm
    privileged: true
    environment:
      # DB settings.
      HAKA_DB_HOST: haka_db
      HAKA_DB_PORT: 5432
      HAKA_DB_NAME: test
      HAKA_DB_PASS: test
      HAKA_DB_USER: test
      # Server settings.
      HAKA_CORS_URL: "http://192.168.0.13:8080"
      HAKA_PORT: 8080
      HAKA_SHIELDS_IO_URL: "https://img.shields.io"
      HAKA_ENABLE_REGISTRATION: "true" # Toggle after you've created your account.
      # Number of hours after which inactive browser sessions will expire (login required).
      HAKA_SESSION_EXPIRY: "24"
    ports:
      - "0.0.0.0:8080:8080"
  haka_db:
    container_name: haka_db
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    volumes:
      - ./docker/:/docker-entrypoint-initdb.d/
      - deploy_db_data:/var/lib/postgresql/data

volumes:
  deploy_db_data: {}
```
